@startuml

Interface MoveInterface {
__package__
public void move(Picture picture, Point point);
}

MoveInterface <|-- MoveLeft : extends
MoveInterface <|-- MoveRight : extends
MoveInterface <|-- MoveUp : extends
MoveInterface <|-- MoveDown : extends

@enduml